#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : koji
Version  : 1.17.0
Release  : 112
URL      : https://pagure.io/koji/archive/koji-1.17.0/koji-koji-1.17.0.tar.gz
Source0  : https://pagure.io/koji/archive/koji-1.17.0/koji-koji-1.17.0.tar.gz
Summary  : Build system tools
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+ LGPL-2.0 LGPL-2.1
Requires: koji-bin = %{version}-%{release}
Requires: koji-libexec = %{version}-%{release}
Requires: koji-license = %{version}-%{release}
Requires: koji-python = %{version}-%{release}
Requires: koji-services = %{version}-%{release}
Requires: Babel
Requires: Cheetah
Requires: Cheetah-legacypython
Requires: Jinja2
Requires: Markdown
Requires: MarkupSafe
Requires: Pygments
Requires: Sphinx
Requires: Whoosh
Requires: alabaster
Requires: argparse
Requires: argparse-legacypython
Requires: asn1crypto
Requires: attrs
Requires: certifi
Requires: cffi
Requires: chardet
Requires: colorama
Requires: coverage
Requires: cryptography
Requires: deprecated-Babel-legacypython
Requires: deprecated-Jinja2-legacypython
Requires: deprecated-Markdown-legacypython
Requires: deprecated-MarkupSafe-legacypython
Requires: deprecated-Pygments-legacypython
Requires: deprecated-Sphinx-legacypython
Requires: deprecated-Whoosh-legacypython
Requires: deprecated-alabaster-legacypython
Requires: deprecated-asn1crypto-legacypython
Requires: deprecated-attrs-legacypython
Requires: deprecated-certifi-legacypython
Requires: deprecated-cffi-legacypython
Requires: deprecated-chardet-legacypython
Requires: deprecated-colorama-legacypython
Requires: deprecated-coverage-legacypython
Requires: deprecated-cryptography-legacypython
Requires: deprecated-docutils-legacypython
Requires: deprecated-funcsigs-legacypython
Requires: deprecated-html5lib-legacypython
Requires: deprecated-idna-legacypython
Requires: deprecated-imagesize-legacypython
Requires: deprecated-ipaddress-legacypython
Requires: deprecated-linecache2-legacypython
Requires: deprecated-nose-legacypython
Requires: deprecated-ordereddict-legacypython
Requires: deprecated-pluggy-legacypython
Requires: deprecated-psycopg2-legacypython
Requires: deprecated-py-legacypython
Requires: deprecated-pyOpenSSL-legacypython
Requires: deprecated-pycparser-legacypython
Requires: deprecated-python-mock-legacypython
Requires: deprecated-python-multilib-legacypython
Requires: deprecated-pytz-legacypython
Requires: deprecated-requests-legacypython
Requires: deprecated-simplejson-legacypython
Requires: deprecated-six-legacypython
Requires: deprecated-snowballstemmer-legacypython
Requires: deprecated-sphinx_rtd_theme-legacypython
Requires: deprecated-sphinxcontrib-websupport-legacypython
Requires: deprecated-traceback2-legacypython
Requires: deprecated-typing-legacypython
Requires: deprecated-urllib3-legacypython
Requires: deprecated-zope.testing-legacypython
Requires: deprecated-zope.testrunner-legacypython
Requires: docutils
Requires: funcsigs
Requires: git
Requires: html5lib
Requires: idna
Requires: imagesize
Requires: ipaddress
Requires: koji-doc
Requires: koji-legacypython
Requires: libcomps
Requires: linecache2
Requires: nose
Requires: ordereddict
Requires: pbr
Requires: pbr-legacypython
Requires: pluggy
Requires: psycopg2
Requires: py
Requires: pyOpenSSL
Requires: pycparser
Requires: python-dateutil
Requires: python-dateutil-legacypython
Requires: python-dateutil-legacypython-legacypython
Requires: python-krbV
Requires: python-krbV-legacypython
Requires: python-mock
Requires: python-multilib
Requires: python-rpm
Requires: pytz
Requires: requests
Requires: rpm
Requires: setuptools
Requires: setuptools-legacypython
Requires: simplejson
Requires: six
Requires: snowballstemmer
Requires: sphinx_rtd_theme
Requires: sphinxcontrib-websupport
Requires: traceback2
Requires: typing
Requires: urlgrabber
Requires: urlgrabber-legacypython
Requires: urllib3
Requires: yum
Requires: yum-legacypython
Requires: yum-metadata-parser
Requires: yum-metadata-parser-python
Requires: zope.testing
Requires: zope.testrunner
BuildRequires : Babel
BuildRequires : Cheetah
BuildRequires : Jinja2
BuildRequires : Markdown
BuildRequires : MarkupSafe
BuildRequires : Pygments
BuildRequires : Sphinx
BuildRequires : Whoosh
BuildRequires : alabaster
BuildRequires : argparse
BuildRequires : asn1crypto
BuildRequires : attrs
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3
BuildRequires : certifi
BuildRequires : cffi
BuildRequires : chardet
BuildRequires : colorama
BuildRequires : coverage
BuildRequires : cryptography
BuildRequires : docutils
BuildRequires : funcsigs
BuildRequires : git
BuildRequires : html5lib
BuildRequires : idna
BuildRequires : imagesize
BuildRequires : ipaddress
BuildRequires : libcomps
BuildRequires : linecache2
BuildRequires : nose
BuildRequires : ordereddict
BuildRequires : pbr
BuildRequires : pkgconfig(systemd)
BuildRequires : pluggy
BuildRequires : psycopg2
BuildRequires : py
BuildRequires : pyOpenSSL
BuildRequires : pycparser
BuildRequires : python-dateutil
BuildRequires : python-dateutil-legacypython
BuildRequires : python-dev
BuildRequires : python-krbV
BuildRequires : python-mock
BuildRequires : python-multilib
BuildRequires : pytz
BuildRequires : requests
BuildRequires : rpm
BuildRequires : setuptools
BuildRequires : setuptools-legacypython
BuildRequires : simplejson
BuildRequires : six
BuildRequires : snowballstemmer
BuildRequires : sphinxcontrib-websupport
BuildRequires : systemd-dev
BuildRequires : traceback2
BuildRequires : typing
BuildRequires : urlgrabber
BuildRequires : urllib3
BuildRequires : yum
BuildRequires : yum-metadata-parser
BuildRequires : zope.testing
BuildRequires : zope.testrunner
Patch1: 0001-builder-use-sudo-to-call-mock.patch
Patch2: 0002-Use-old-version-of-NSS-forking-behavior.patch
Patch3: 0003-Change-install-dir-to-usr-bin.patch
Patch4: 0004-Do-not-build-kojivm.patch
Patch5: 0005-Close-koji-db-connections.patch
Patch6: 0006-kojira-fix-iteration-over-repos-in-py3.patch

%description
Koji is a system for building and tracking RPMS.  The base package
contains shared libraries and the command-line interface.

%package bin
Summary: bin components for the koji package.
Group: Binaries
Requires: koji-libexec = %{version}-%{release}
Requires: koji-license = %{version}-%{release}
Requires: koji-services = %{version}-%{release}

%description bin
bin components for the koji package.


%package doc
Summary: doc components for the koji package.
Group: Documentation

%description doc
doc components for the koji package.


%package extras
Summary: extras components for the koji package.
Group: Default

%description extras
extras components for the koji package.


%package legacypython
Summary: legacypython components for the koji package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the koji package.


%package libexec
Summary: libexec components for the koji package.
Group: Default
Requires: koji-license = %{version}-%{release}

%description libexec
libexec components for the koji package.


%package license
Summary: license components for the koji package.
Group: Default

%description license
license components for the koji package.


%package python
Summary: python components for the koji package.
Group: Default

%description python
python components for the koji package.


%package services
Summary: services components for the koji package.
Group: Systemd services

%description services
services components for the koji package.


%prep
%setup -q -n koji-koji-1.17.0
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1
%patch5 -p1
%patch6 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1563231307
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$CFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$CFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export MAKEFLAGS=%{?_smp_mflags}
python2 setup.py build -b py2

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/koji
cp COPYING %{buildroot}/usr/share/package-licenses/koji/COPYING
python2 -tt setup.py build -b py2 install --root=%{buildroot}
## install_append content
/usr/bin/make DESTDIR=%{buildroot} PYTHON=python2 install
mkdir -p %{buildroot}/usr/share/doc/koji/
mv %{buildroot}/etc %{buildroot}/usr/share/doc/koji/
cp -a docs  %{buildroot}/usr/share/doc/koji/
find %{buildroot} -name "*.pyc" | xargs rm
## install_append end

%files
%defattr(-,root,root,-)
/usr/lib/koji-builder-plugins/runroot.py
/usr/lib/koji-builder-plugins/save_failed_tree.py
/usr/lib/koji-hub-plugins/echo.py
/usr/lib/koji-hub-plugins/protonmsg.py
/usr/lib/koji-hub-plugins/rpm2maven.py
/usr/lib/koji-hub-plugins/runroot_hub.py
/usr/lib/koji-hub-plugins/save_failed_tree.py

%files bin
%defattr(-,root,root,-)
/usr/bin/koji
/usr/bin/koji-gc
/usr/bin/koji-shadow
/usr/bin/kojid
/usr/bin/kojira

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/koji/*

%files extras
%defattr(-,root,root,-)
/usr/share/koji-hub/__init__.py
/usr/share/koji-hub/kojihub.py
/usr/share/koji-hub/kojixmlrpc.py
/usr/share/koji-web/lib/kojiweb/__init__.py
/usr/share/koji-web/lib/kojiweb/util.py
/usr/share/koji-web/scripts/archiveinfo.chtml
/usr/share/koji-web/scripts/archivelist.chtml
/usr/share/koji-web/scripts/buildinfo.chtml
/usr/share/koji-web/scripts/buildrootinfo.chtml
/usr/share/koji-web/scripts/buildrootinfo_cg.chtml
/usr/share/koji-web/scripts/builds.chtml
/usr/share/koji-web/scripts/buildsbystatus.chtml
/usr/share/koji-web/scripts/buildsbytarget.chtml
/usr/share/koji-web/scripts/buildsbyuser.chtml
/usr/share/koji-web/scripts/buildtargetedit.chtml
/usr/share/koji-web/scripts/buildtargetinfo.chtml
/usr/share/koji-web/scripts/buildtargets.chtml
/usr/share/koji-web/scripts/channelinfo.chtml
/usr/share/koji-web/scripts/error.chtml
/usr/share/koji-web/scripts/externalrepoinfo.chtml
/usr/share/koji-web/scripts/fileinfo.chtml
/usr/share/koji-web/scripts/hostedit.chtml
/usr/share/koji-web/scripts/hostinfo.chtml
/usr/share/koji-web/scripts/hosts.chtml
/usr/share/koji-web/scripts/imageinfo.chtml
/usr/share/koji-web/scripts/includes/footer.chtml
/usr/share/koji-web/scripts/includes/header.chtml
/usr/share/koji-web/scripts/index.chtml
/usr/share/koji-web/scripts/index.py
/usr/share/koji-web/scripts/notificationedit.chtml
/usr/share/koji-web/scripts/packageinfo.chtml
/usr/share/koji-web/scripts/packages.chtml
/usr/share/koji-web/scripts/packagesbyuser.chtml
/usr/share/koji-web/scripts/recentbuilds.chtml
/usr/share/koji-web/scripts/reports.chtml
/usr/share/koji-web/scripts/rpminfo.chtml
/usr/share/koji-web/scripts/rpmlist.chtml
/usr/share/koji-web/scripts/rpmsbyhost.chtml
/usr/share/koji-web/scripts/search.chtml
/usr/share/koji-web/scripts/searchresults.chtml
/usr/share/koji-web/scripts/tagedit.chtml
/usr/share/koji-web/scripts/taginfo.chtml
/usr/share/koji-web/scripts/tagparent.chtml
/usr/share/koji-web/scripts/tags.chtml
/usr/share/koji-web/scripts/taskinfo.chtml
/usr/share/koji-web/scripts/tasks.chtml
/usr/share/koji-web/scripts/tasksbyhost.chtml
/usr/share/koji-web/scripts/tasksbyuser.chtml
/usr/share/koji-web/scripts/userinfo.chtml
/usr/share/koji-web/scripts/users.chtml
/usr/share/koji-web/scripts/wsgi_publisher.py
/usr/share/koji-web/static/debug.css
/usr/share/koji-web/static/errors/unauthorized.html
/usr/share/koji-web/static/images/1px.gif
/usr/share/koji-web/static/images/assigned.png
/usr/share/koji-web/static/images/bkgrnd_greydots.png
/usr/share/koji-web/static/images/building.png
/usr/share/koji-web/static/images/canceled.png
/usr/share/koji-web/static/images/closed.png
/usr/share/koji-web/static/images/complete.png
/usr/share/koji-web/static/images/deleted.png
/usr/share/koji-web/static/images/expired.png
/usr/share/koji-web/static/images/failed.png
/usr/share/koji-web/static/images/free.png
/usr/share/koji-web/static/images/gray-triangle-down.gif
/usr/share/koji-web/static/images/gray-triangle-up.gif
/usr/share/koji-web/static/images/init.png
/usr/share/koji-web/static/images/initializing.png
/usr/share/koji-web/static/images/koji.ico
/usr/share/koji-web/static/images/koji.png
/usr/share/koji-web/static/images/no.png
/usr/share/koji-web/static/images/open.png
/usr/share/koji-web/static/images/powered-by-koji.png
/usr/share/koji-web/static/images/ready.png
/usr/share/koji-web/static/images/unknown.png
/usr/share/koji-web/static/images/waiting.png
/usr/share/koji-web/static/images/yes.png
/usr/share/koji-web/static/js/watchlogs.js
/usr/share/koji-web/static/koji.css
/usr/share/koji-web/static/themes/README

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files libexec
%defattr(-,root,root,-)
/usr/libexec/kojid/mergerepos

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/koji/COPYING

%files python
%defattr(-,root,root,-)

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/kojid.service
/usr/lib/systemd/system/kojira.service
